In [1]:
import pandas as pd
import os as os
import cv2
import numpy as np
from matplotlib import pyplot as plt
from sklearn.cluster import KMeans # cluster algorithm
import math

%matplotlib inline
import mpld3
mpld3.enable_notebook()

#Variables
ID = 'NaN'
size_wiki = 'NaN'
size_nkb = 'NaN'
foot_length_cm = 'NaN'
foot_length_dots = 'NaN'
foot_width_cm = 'NaN'
foot_width_dots = 'NaN'
Fersenbreite_cm = 'NaN'
Fersenbreite_dots = 'NaN'
Ballenbreite_cm = 'NaN'
Ballenbreite_dots = 'NaN'
D5_x_cm = 'NaN'
D4_x_cm = 'NaN'
D3_x_cm = 'NaN'
D2_x_cm = 'NaN'
D1_x_cm = 'NaN'
D5_y_cm = 'NaN'
D4_y_cm = 'NaN'
D3_y_cm = 'NaN'
D2_y_cm = 'NaN'
D1_y_cm = 'NaN'
average_D3_D2 = 'NaN'
average_D5toD2 = 'NaN'
average_toeRamp = 'NaN'
angle_D5_D3 = 'NaN'
angle_D2_D1 = 'NaN'
angle_ToeRamp = 'NaN'

In [2]:
%run AnalyseFootScan.ipynb

Points after distribution:
[[  8 273]
 [ 55 195]
 [ 98 155]
 [137 131]
 [176 129]
 [249 140]
 [296 215]
 [ 96 682]
 [181 752]
 [249 679]]
Fersenbreite_dots: 153
Fersenbreite_cm: 5.4
Ballenbreite_cm: 10.16
average_D3_D2: 21.9
average_D5_D2: 21.2
average_toeRamp: 21.2
angle_Toeramp: 133.0
Points after distribution:
[[116.  166. ]
 [149.  123. ]
 [176.5 102. ]
 [178.5 101. ]
 [218.   92. ]
 [296.  108. ]
 [339.  179. ]
 [ 84.  230. ]
 [120.  567. ]
 [302.  584. ]]
Fersenbreite_dots: 218.0
Fersenbreite_cm: 7.69
Ballenbreite_cm: 7.87
average_D3_D2: 16.6
average_D5_D2: 16.3
average_toeRamp: 16.3
angle_Toeramp: 131.0


In [3]:
#Analyze all Pictures
#Initilaize Folder with Footscans
#listOfAllFiles = os.listdir(path = "/Fussscans")
pathFolder = "C:\\Users\\Fabian\\Desktop\\GIThub\\AnalyzingFootData\\"
listOfAllFiles = os.listdir(path = pathFolder)#\\sortiertName")#FussScansSelection")
#listOfAllFiles = os.listdir(path = "F:\\Dropbox\\ADICS\\22_Grundlagenentwicklung\\Fussscans")
#listOfAllFiles = os.listdir(path = "F:\\Dropbox\\ADICS\\22_Grundlagenentwicklung") #\\usefulrest")

listOfAllScans = []
for scans in listOfAllFiles:
    if scans.endswith(".JPG"):
        listOfAllScans.append(scans)
        #print (scans)
#print (listOfAllScans)

In [4]:
#Creates Dataframe with Columns
df = pd.DataFrame(columns=['ID','Size_wiki', 'Size_NKB','Length_cm', 'Length_dots','Width_cm', 'Width_dots',
                           'Fersenbreite_cm', 'Fersenbreite_dots', 'Ballenbreite_cm', 'Ballenbreite_dots',
                           'D5_x_cm','D4_x_cm','D3_x_cm','D2_x_cm','D1_x_cm',
                           'D5_y_cm','D4_y_cm','D3_y_cm','D2_y_cm','D1_y_cm','angle_D5_D3','angle_D2_D1','angle_ToeRamp'])

#Limits Numer of scans
i = 0
i_start = 0 
i_end = 245 #write a number higher den the count of the scans to run all
#Do it for defined scans in the chosen folder
print(listOfAllScans)
for scan in listOfAllScans:
    ID = 'NaN' #sets every value back to NaN
    size_wiki = 'NaN'
    size_nkb = 'NaN'
    foot_length_cm = 'NaN'
    foot_length_dots = 'NaN'
    foot_width_cm = 'NaN'
    foot_width_dots = 'NaN'
    Fersenbreite_cm = 'NaN'
    Fersenbreite_dots = 'NaN'
    Ballenbreite_cm = 'NaN'
    Ballenbreite_dots = 'NaN'
    D5_x_cm = 'NaN'
    D4_x_cm = 'NaN'
    D3_x_cm = 'NaN'
    D2_x_cm = 'NaN'
    D1_x_cm = 'NaN'
    D5_y_cm = 'NaN'
    D4_y_cm = 'NaN'
    D3_y_cm = 'NaN'
    D2_y_cm = 'NaN'
    D1_y_cm = 'NaN'
    average_D3_D2 = 'NaN'
    average_D5toD2 = 'NaN'
    average_toeRamp = 'NaN'
    angle_D5_D3 = 'NaN'
    angle_D2_D1 = 'NaN'
    angle_ToeRamp = 'NaN'
    if i >= i_start and i <= i_end:
        print (scan) 
        try:
            image = cv2.imread(scan) # load image
            foot_length_cm, foot_length_dots, foot_width_cm, foot_width_dots = analyseFootScan(image, False) # Boolean specifies whether visualization is done

            ID = scan.strip(".JPG")
            #Define Size
            #nach Wikipedia: 
            #Schuhgröße (EU) ≈ (Fußlänge in cm + 1,5) × 1,5    // Rundung auf halbe Größen
            size_wiki = round((foot_length_cm + 1.5)*1.5 * 2) / 2
            size_nkb = size_wiki -1
        except:
            print (scan + "error occured")
        try: 
            filePathPNG = pathFolder + ID + '.png'#'C:\\Users\\Fabian\\Desktop\\GIThub\\AnalyzingFootData\\'+ ID + '.png'
            print(filePathPNG)
            if os.path.isfile(filePathPNG):
                image = plt.imread(filePathPNG) # load image
                Fersenbreite_dots, Fersenbreite_cm, Ballenbreite_dots, Ballenbreite_cm, D5_x_cm, D4_x_cm, D3_x_cm,D2_x_cm,D1_x_cm, D5_y_cm, D4_y_cm, D3_y_cm,D2_y_cm,D1_y_cm, average_D3_D2,average_D5toD2, average_toeRamp,angle_D5_D3, angle_D2_D1, angle_ToeRamp = readBluePointsOfFootScan_cluster(image, False)
            else:
                print(ID +'.png' + ' does not exists')
        except:
                print(ID +'.png' + ' ERROR occured')
        try:    
            df = df.append({'ID': ID,'Size_wiki':size_wiki, 'Size_NKB':size_nkb, 
                            'Length_cm': foot_length_cm, 'Length_dots': foot_length_dots,
                            'Width_cm': foot_width_cm, 'Width_dots': foot_width_dots, 'Fersenbreite_cm': Fersenbreite_cm,'Fersenbreite_dots': Fersenbreite_dots,
                            'Ballenbreite_cm':Ballenbreite_cm, 'Ballenbreite_dots': Ballenbreite_dots,
                            'D5_x_cm': D5_x_cm,'D4_x_cm':D4_x_cm ,'D3_x_cm':D3_x_cm,'D2_x_cm':D2_x_cm,'D1_x_cm':D1_x_cm,
                            'D5_y_cm': D5_y_cm,'D4_y_cm':D4_y_cm,'D3_y_cm':D3_y_cm,'D2_y_cm':D2_y_cm,'D1_y_cm':D1_y_cm,
                            'average_D3_D2':average_D3_D2,'average_D5toD2':average_D5toD2,
                            'angle_D5_D3':angle_D5_D3,'angle_D2_D1':angle_D2_D1,
                            'average_toeRamp':average_toeRamp,'angle_ToeRamp':angle_ToeRamp},
                                    ignore_index = True)  #Append data to DataFrame   
        except:
                print(ID + " error while writing data to dataframe")
    i= i+1
    
df

['20090313145121.JPG', '20090803090905.JPG', '20090804153556.JPG', '20091102094852.JPG', '20100312135858.JPG', '20100318164506.JPG', '20100506103413.JPG', '20100923102819.JPG', '20101021111204.JPG', '20101027123753.JPG', '20110128133823.JPG', '20110303160502.JPG', '20110504154325.JPG', '20110526173420.JPG', '20110705110429.JPG', '20110718085206.JPG', '20110725131630.JPG', '20110802093952.JPG', '20110805143308.JPG', '20110809103333.JPG', '20110810153421.JPG', '20110812105217.JPG', '20110826122923.JPG', '20110909134916.JPG', '20111021104429.JPG', '20111025152623.JPG', '20111028120743.JPG', '20111103103711.JPG', '20111124082758.JPG', '20120105115549.JPG', '20120124090602.JPG', '20120206094439.JPG', '20120313115231.JPG', '20120412120808.JPG', '20120526143052.JPG', '20120604100746.JPG', '20120612085935.JPG', '20120727110331.JPG', '20120727112128.JPG', '20120830160403.JPG', '20120906124658.JPG', '20120918124850.JPG', '20120924141153.JPG', '20120925133211.JPG', '20121212155930.JPG', '20130122

Foot length is 26.49 cm.
Foot width is 10.55 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\20090313145121.png
Points after distribution:
[[  8 273]
 [ 55 195]
 [ 98 155]
 [137 131]
 [176 129]
 [249 140]
 [296 215]
 [ 96 682]
 [181 752]
 [249 679]]
Fersenbreite_dots: 153
Fersenbreite_cm: 5.4
Ballenbreite_cm: 10.16
average_D3_D2: 21.9
average_D5_D2: 21.2
average_toeRamp: 21.2
angle_Toeramp: 133.0
20090803090905.JPG
Foot length is 26.32 cm.
Foot width is 10.34 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\20090803090905.png
Points after distribution:
[[  8 293]
 [ 44 202]
 [ 76 160]
 [117 134]
 [166 123]
 [245 149]
 [292 219]
 [ 60 646]
 [156 750]
 [247 649]]
Fersenbreite_dots: 187
Fersenbreite_cm: 6.6
Ballenbreite_cm: 10.02
average_D3_D2: 21.9
average_D5_D2: 21.0
average_toeRamp: 21.0
angle_Toeramp: 119.0
20090804153556.JPG
Foot length is 27.69 cm.
Foot width is 10.76 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\20090804153556.png
Points after distribution:
[[  9.  

Foot length is 25.93 cm.
Foot width is 8.96 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\20110802093952.png
Points after distribution:
[[  7. 271.]
 [ 35. 179.]
 [ 61. 145.]
 [105. 117.]
 [144. 108.]
 [231. 144.]
 [256. 196.]
 [ 42. 640.]
 [144. 736.]
 [238. 637.]]
Fersenbreite_dots: 196.0
Fersenbreite_cm: 6.91
Ballenbreite_cm: 8.78
average_D3_D2: 22.0
average_D5_D2: 21.1
average_toeRamp: 21.1
angle_Toeramp: 116.0
20110805143308.JPG
Foot length is 26.32 cm.
Foot width is 10.72 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\20110805143308.png
Points after distribution:
[[  7.  281. ]
 [ 32.  199. ]
 [ 94.5 142. ]
 [125.  119. ]
 [182.  110. ]
 [264.  136. ]
 [303.  224. ]
 [ 70.  651. ]
 [168.  738. ]
 [254.  642. ]]
Fersenbreite_dots: 184.0
Fersenbreite_cm: 6.49
Ballenbreite_cm: 10.44
average_D3_D2: 22.0
average_D5_D2: 21.0
average_toeRamp: 21.1
angle_Toeramp: 122.0
20110809103333.JPG
Foot length is 28.26 cm.
Foot width is 11.61 cm.
C:\Users\Fabian\Desktop\GIThub\Analyzin

Foot length is 27.09 cm.
Foot width is 11.18 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\20120412120808.png
Points after distribution:
[[  7.  301. ]
 [ 33.5 236. ]
 [ 78.  187. ]
 [117.  155. ]
 [160.  145. ]
 [247.  149. ]
 [315.  229.5]
 [ 75.  680. ]
 [169.  765. ]
 [259.  662. ]]
Fersenbreite_dots: 184.0
Fersenbreite_cm: 6.49
Ballenbreite_cm: 10.87
average_D3_D2: 21.7
average_D5_D2: 20.6
average_toeRamp: 20.8
angle_Toeramp: 133.0
20120526143052.JPG
Foot length is 24.59 cm.
Foot width is 9.91 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\20120526143052.png
Points after distribution:
[[  7.  255. ]
 [ 36.  180. ]
 [ 69.  148.4]
 [104.  121. ]
 [157.  105. ]
 [238.  128. ]
 [275.  203.5]
 [ 65.  613. ]
 [180.  701. ]
 [248.  627. ]]
Fersenbreite_dots: 183.0
Fersenbreite_cm: 6.46
Ballenbreite_cm: 9.45
average_D3_D2: 20.7
average_D5_D2: 19.8
average_toeRamp: 19.9
angle_Toeramp: 123.0
20120604100746.JPG
Foot length is 23.57 cm.
Foot width is 10.12 cm.
C:\Users\Fabian\Des

Points after distribution:
[[ 14.         281.        ]
 [ 37.         230.        ]
 [ 70.         179.        ]
 [ 95.         151.        ]
 [136.         141.        ]
 [207.         144.        ]
 [249.33333333 193.33333333]
 [ 83.         583.        ]
 [176.         673.        ]
 [247.         583.        ]]
Fersenbreite_dots: 164.0
Fersenbreite_cm: 5.79
Ballenbreite_cm: 8.3
average_D3_D2: 18.6
average_D5_D2: 17.6
average_toeRamp: 17.8
angle_Toeramp: 124.0
20130312111021.JPG
Foot length is 28.4 cm.
Foot width is 10.65 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\20130312111021.png
Points after distribution:
[[ 13.         291.        ]
 [ 62.66666667 207.66666667]
 [108.         154.5       ]
 [139.5        129.        ]
 [184.         125.7       ]
 [261.         147.        ]
 [312.         224.        ]
 [ 96.         703.5       ]
 [202.         803.5       ]
 [284.         683.        ]]
Fersenbreite_dots: 188.0
Fersenbreite_cm: 6.63
Ballenbreite_cm: 10.55
average_

Foot length is 21.45 cm.
Foot width is 7.66 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\20140319152850.png
Points after distribution:
[[ 15.   220.  ]
 [ 29.   156.  ]
 [ 57.   126.  ]
 [ 91.25 101.75]
 [128.5   97.  ]
 [197.   117.  ]
 [221.   177.  ]
 [ 53.   539.  ]
 [121.   603.  ]
 [174.   539.  ]]
Fersenbreite_dots: 121.0
Fersenbreite_cm: 4.27
Ballenbreite_cm: 7.27
average_D3_D2: 17.8
average_D5_D2: 17.0
average_toeRamp: 17.1
angle_Toeramp: 123.0
20140430151440.JPG
Foot length is 22.79 cm.
Foot width is 8.71 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\20140430151440.png
Points after distribution:
[[  6.  280.5]
 [ 31.  200. ]
 [ 73.  159. ]
 [102.  132. ]
 [139.  118. ]
 [204.  134. ]
 [241.  204. ]
 [ 54.  586. ]
 [149.  673. ]
 [226.  575. ]]
Fersenbreite_dots: 172.0
Fersenbreite_cm: 6.07
Ballenbreite_cm: 8.29
average_D3_D2: 19.3
average_D5_D2: 18.4
average_toeRamp: 18.5
angle_Toeramp: 122.0
20140527093711.JPG
Foot length is 30.87 cm.
Foot width is 12.1 cm.
C:

Points after distribution:
[[  6. 264.]
 [ 38. 182.]
 [ 82. 144.]
 [115. 118.]
 [168. 111.]
 [239. 136.]
 [280. 203.]
 [ 61. 618.]
 [147. 708.]
 [225. 618.]]
Fersenbreite_dots: 164.0
Fersenbreite_cm: 5.79
Ballenbreite_cm: 9.67
average_D3_D2: 20.9
average_D5_D2: 20.1
average_toeRamp: 20.1
angle_Toeramp: 121.0
20150717153532.JPG
Foot length is 24.09 cm.
Foot width is 9.03 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\20150717153532.png
Points after distribution:
[[ 13 250]
 [ 33 188]
 [ 68 153]
 [104 128]
 [148 118]
 [210 129]
 [261 206]
 [ 53 603]
 [143 685]
 [217 597]]
Fersenbreite_dots: 164
Fersenbreite_cm: 5.79
Ballenbreite_cm: 8.75
average_D3_D2: 19.8
average_D5_D2: 19.0
average_toeRamp: 19.1
angle_Toeramp: 130.0
20150721133414.JPG
Foot length is 26.42 cm.
Foot width is 10.02 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\20150721133414.png
Points after distribution:
[[ 47 182]
 [ 80 139]
 [118 116]
 [161 107]
 [161 108]
 [244 150]
 [279 229]
 [  6 272]
 [ 51 654]
 [239

Foot length is 26.32 cm.
Foot width is 10.44 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Arand---_----2453_----4510_000L.png
Points after distribution:
[[  8.  267. ]
 [ 45.  189. ]
 [ 88.  147. ]
 [124.  123. ]
 [167.  107.5]
 [241.  129. ]
 [294.  206. ]
 [ 73.  648. ]
 [169.  753. ]
 [242.  646. ]]
Fersenbreite_dots: 169.0
Fersenbreite_cm: 5.96
Ballenbreite_cm: 10.09
average_D3_D2: 22.5
average_D5_D2: 21.6
average_toeRamp: 21.7
angle_Toeramp: 124.0
Arles---_----2462_----4527_000L.JPG
Foot length is 25.82 cm.
Foot width is 10.62 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Arles---_----2462_----4527_000L.png
Points after distribution:
[[  7 274]
 [ 33 208]
 [ 87 152]
 [130 127]
 [185 123]
 [257 152]
 [295 225]
 [ 76 652]
 [169 738]
 [248 646]]
Fersenbreite_dots: 172
Fersenbreite_cm: 6.07
Ballenbreite_cm: 10.16
average_D3_D2: 21.6
average_D5_D2: 20.7
average_toeRamp: 20.7
angle_Toeramp: 118.0
Ascherl-_----2425_----4457_000L.JPG
Foot length is 27.52 cm.
Foot width is 1

Foot length is 27.06 cm.
Foot width is 9.6 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Baerenz--_----2267_----4086_000L.png
Points after distribution:
[[  6 285]
 [ 37 206]
 [ 72 161]
 [112 128]
 [154 121]
 [238 150]
 [272 215]
 [ 53 653]
 [159 770]
 [249 663]]
Fersenbreite_dots: 196
Fersenbreite_cm: 6.91
Ballenbreite_cm: 9.38
average_D3_D2: 22.8
average_D5_D2: 21.7
average_toeRamp: 21.8
angle_Toeramp: 115.0
Baeumler-_-----269_----3043_000L.JPG
Foot length is 26.88 cm.
Foot width is 10.51 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Baeumler-_-----269_----3043_000L.png
Points after distribution:
[[  6.  287. ]
 [ 38.  200. ]
 [ 91.2 149.2]
 [130.5 125.5]
 [176.  117. ]
 [252.5 138.5]
 [295.  211. ]
 [ 80.  648. ]
 [183.  765.5]
 [274.  668. ]]
Fersenbreite_dots: 194.0
Fersenbreite_cm: 6.84
Ballenbreite_cm: 10.2
average_D3_D2: 22.7
average_D5_D2: 21.8
average_toeRamp: 21.9
angle_Toeramp: 125.0
Bahceci-_----1607_----3266_000R.JPG
Foot length is 26.88 cm.
Foot width is 9.

Foot length is 26.35 cm.
Foot width is 10.58 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Bauer---_-----252_-----286_042L.png
Points after distribution:
[[  5.         285.5       ]
 [ 45.         189.        ]
 [ 77.         155.        ]
 [124.         120.        ]
 [174.         112.        ]
 [249.         148.        ]
 [295.         210.        ]
 [ 79.         660.        ]
 [167.33333333 746.33333333]
 [249.         664.        ]]
Fersenbreite_dots: 170.0
Fersenbreite_cm: 6.0
Ballenbreite_cm: 10.23
average_D3_D2: 22.2
average_D5_D2: 21.2
average_toeRamp: 21.2
angle_Toeramp: 113.0
Bauer---_----1014_----1441_000L.JPG
Foot length is 28.01 cm.
Foot width is 10.76 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Bauer---_----1014_----1441_000L.png
Points after distribution:
[[ 16.  315. ]
 [ 47.  232. ]
 [ 94.  182. ]
 [139.  148. ]
 [183.  139. ]
 [270.  160. ]
 [307.  253. ]
 [ 76.5 687. ]
 [169.  791. ]
 [253.  705. ]]
Fersenbreite_dots: 176.5
Fersenbreite_cm: 6.23
B

Points after distribution:
[[  8 328]
 [ 50 223]
 [113 166]
 [152 134]
 [181 137]
 [275 185]
 [305 257]
 [ 83 683]
 [170 776]
 [256 692]]
Fersenbreite_dots: 173
Fersenbreite_cm: 6.1
Ballenbreite_cm: 10.48
average_D3_D2: 22.6
average_D5_D2: 21.6
average_toeRamp: 21.4
angle_Toeramp: 112.0
Beier---_-----947_----1327_000L.JPG
Foot length is 26.85 cm.
Foot width is 10.58 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Beier---_-----947_----1327_000L.png
Points after distribution:
[[  9.  294. ]
 [ 44.  196. ]
 [ 93.  145. ]
 [134.5 123. ]
 [190.  109. ]
 [263.  143. ]
 [297.  234. ]
 [ 69.  649. ]
 [164.  756. ]
 [249.  675. ]]
Fersenbreite_dots: 180.0
Fersenbreite_cm: 6.35
Ballenbreite_cm: 10.16
average_D3_D2: 22.6
average_D5_D2: 21.6
average_toeRamp: 21.6
angle_Toeramp: 116.0
Bell----_----2052_----3569_000L.JPG
Foot length is 22.72 cm.
Foot width is 9.0 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Bell----_----2052_----3569_000L.png
Points after distribution:
[[ 15 243]
 [ 31

Foot length is 26.18 cm.
Foot width is 11.01 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Birkmann_------85_----1729_000L.png
Points after distribution:
[[  7.  282. ]
 [ 54.  186. ]
 [105.  135. ]
 [150.  114. ]
 [199.  112. ]
 [282.  151. ]
 [312.  226.5]
 [ 75.  660. ]
 [172.  746.5]
 [262.  648. ]]
Fersenbreite_dots: 187.0
Fersenbreite_cm: 6.6
Ballenbreite_cm: 10.76
average_D3_D2: 22.3
average_D5_D2: 21.5
average_toeRamp: 21.4
angle_Toeramp: 118.0
Birkmann_-----406_-----473_000L.JPG
Foot length is 28.29 cm.
Foot width is 10.9 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Birkmann_-----406_-----473_000L.png
Points after distribution:
[[  7 298]
 [ 49 195]
 [ 89 154]
 [126 126]
 [183 120]
 [261 150]
 [305 255]
 [ 61 681]
 [167 805]
 [261 688]]
Fersenbreite_dots: 200
Fersenbreite_cm: 7.06
Ballenbreite_cm: 10.51
average_D3_D2: 24.1
average_D5_D2: 23.2
average_toeRamp: 23.1
angle_Toeramp: 117.0
Birkmann_----1010_----1432_000L.JPG
Foot length is 28.47 cm.
Foot width is 10.

Foot length is 26.07 cm.
Foot width is 10.02 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Borgmann_-----356_-----414_000L.png
Points after distribution:
[[  8 268]
 [ 58 182]
 [ 90 139]
 [120 119]
 [160 114]
 [244 149]
 [281 215]
 [ 65 648]
 [151 742]
 [238 655]]
Fersenbreite_dots: 173
Fersenbreite_cm: 6.1
Ballenbreite_cm: 9.63
average_D3_D2: 22.1
average_D5_D2: 21.3
average_toeRamp: 21.2
angle_Toeramp: 112.0
Brand---_-----280_-----320_039L.JPG
Foot length is 24.09 cm.
Foot width is 9.35 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Brand---_-----280_-----320_039L.png
Points after distribution:
[[  9.         262.        ]
 [ 35.         192.        ]
 [ 72.         147.        ]
 [112.         110.        ]
 [157.         104.        ]
 [237.         137.        ]
 [264.         195.        ]
 [ 59.5        579.        ]
 [147.         683.        ]
 [226.66666667 598.        ]]
Fersenbreite_dots: 167.16666666666666
Fersenbreite_cm: 5.9
Ballenbreite_cm: 9.0
average_D3_D

Foot length is 24.8 cm.
Foot width is 9.17 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Bruesehab_-----331_----2086_000L.png
Points after distribution:
[[ 10.  288.5]
 [ 33.  202. ]
 [ 62.  163. ]
 [102.  131. ]
 [152.  121. ]
 [214.  142. ]
 [259.  210. ]
 [ 10.  290. ]
 [ 50.  607.5]
 [214.  630. ]]
Fersenbreite_dots: 204.0
Fersenbreite_cm: 7.2
Ballenbreite_cm: 8.78
average_D3_D2: 17.0
average_D5_D2: 16.0
average_toeRamp: 16.1
angle_Toeramp: 116.0
Bruesehab_-----331_----3855_000L.JPG
Foot length is 24.45 cm.
Foot width is 9.24 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Bruesehab_-----331_----3855_000L.png
Points after distribution:
[[  9.  273. ]
 [ 37.  190. ]
 [ 74.  152. ]
 [120.  123. ]
 [162.  117. ]
 [225.  138.5]
 [262.  211. ]
 [ 54.  602. ]
 [137.  697. ]
 [221.  610. ]]
Fersenbreite_dots: 167.0
Fersenbreite_cm: 5.89
Ballenbreite_cm: 8.93
average_D3_D2: 20.4
average_D5_D2: 19.5
average_toeRamp: 19.5
angle_Toeramp: 122.0
Brugman-_----1413_----2220_000L.JPG
F

Foot length is 25.61 cm.
Foot width is 10.16 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Cermak--_----2195_----3902_000L.png
Points after distribution:
[[  8. 284.]
 [ 50. 204.]
 [ 91. 159.]
 [131. 137.]
 [176. 134.]
 [245. 154.]
 [284. 220.]
 [ 88. 645.]
 [180. 732.]
 [260. 628.]]
Fersenbreite_dots: 172.0
Fersenbreite_cm: 6.07
Ballenbreite_cm: 9.74
average_D3_D2: 21.0
average_D5_D2: 20.2
average_toeRamp: 20.3
angle_Toeramp: 124.0
Chaberny_----1791_----3022_000L.JPG
Foot length is 23.64 cm.
Foot width is 9.21 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Chaberny_----1791_----3022_000L.png
Points after distribution:
[[ 10.33333333 246.66666667]
 [ 40.         167.        ]
 [ 85.         121.        ]
 [122.         104.        ]
 [159.         102.        ]
 [220.         120.        ]
 [262.33333333 183.        ]
 [ 72.         574.        ]
 [159.         666.        ]
 [237.         588.        ]]
Fersenbreite_dots: 165.0
Fersenbreite_cm: 5.82
Ballenbreite_cm: 8.89


Points after distribution:
[[  9.         276.        ]
 [ 37.         204.        ]
 [ 67.         161.66666667]
 [116.         122.        ]
 [163.         114.        ]
 [245.         142.        ]
 [273.         207.        ]
 [ 74.         624.        ]
 [159.         714.        ]
 [232.         644.        ]]
Fersenbreite_dots: 158.0
Fersenbreite_cm: 5.57
Ballenbreite_cm: 9.31
average_D3_D2: 21.0
average_D5_D2: 19.9
average_toeRamp: 19.9
angle_Toeramp: 115.0
Cronimus_----2265_----4083_000L.JPG
Foot length is 24.55 cm.
Foot width is 9.14 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Cronimus_----2265_----4083_000L.png
Points after distribution:
[[ 10.         247.        ]
 [ 36.         177.        ]
 [ 82.         136.5       ]
 [124.         107.        ]
 [155.         104.        ]
 [228.         131.        ]
 [265.33333333 196.33333333]
 [ 53.5        601.        ]
 [147.         699.        ]
 [222.         621.        ]]
Fersenbreite_dots: 168.5
Fersenbreite_cm: 5

Foot length is 24.31 cm.
Foot width is 9.74 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Denk----_----2470_----4550_000L.png
Points after distribution:
[[ 39 225]
 [ 79 157]
 [127 118]
 [161 104]
 [202 102]
 [274 138]
 [306 191]
 [ 96 592]
 [187 692]
 [264 603]]
Fersenbreite_dots: 168
Fersenbreite_cm: 5.93
Ballenbreite_cm: 9.42
average_D3_D2: 20.8
average_D5_D2: 20.2
average_toeRamp: 20.0
angle_Toeramp: 121.0
Denkler-_-----268_-----306_038L.JPG
Foot length is 23.88 cm.
Foot width is 9.35 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Denkler-_-----268_-----306_038L.png
Denkler-_-----268_-----306_038L.png does not exists
Dennstaed_----1321_----2035_039L.JPG
Foot length is 24.62 cm.
Foot width is 9.88 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\Dennstaed_----1321_----2035_039L.png
Dennstaed_----1321_----2035_039L.png does not exists
Depmeier_----1973_----3400_000L.JPG
Foot length is 27.3 cm.
Foot width is 9.67 cm.
C:\Users\Fabian\Desktop\GIThub\AnalyzingFootData\De

ID Size_wiki Size_NKB Length_cm  \
0                      20090313145121        42       41     26.49   
1                      20090803090905      41.5     40.5     26.32   
2                      20090804153556        44       43     27.69   
3                      20091102094852        37       36     23.25   
4                      20100312135858      43.5     42.5     27.62   
5                      20100318164506        43       42      27.3   
6                      20100506103413        36       35     22.47   
7                      20100923102819        41       40     25.82   
8                      20101021111204      37.5     36.5     23.46   
9                      20101027123753      38.5     37.5     24.06   
10                     20110128133823        40       39     25.15   
11                     20110303160502      42.5     41.5     26.95   
12                     20110504154325        44       43     27.83   
13                     20110526173420      39.5     38.5     24.77   
14                     20110705110429      42.5     41.5     26.95   
15                     20110718085206      38.5     37.5     24.13   
16                     20110725131630        40       39     25.05   
17                     20110802093952        41       40     25.93   
18                     20110805143308      41.5     40.5     26.32   
19                     20110809103333      44.5     43.5     28.26   
20                     20110810153421        44       43     27.87   
21                     20110812105217      32.5     31.5     20.14   
22                     20110826122923      43.5     42.5     27.45   
23                     20110909134916        40       39     25.29   
24                     20111021104429      40.5     39.5      25.4   
25                     20111025152623      34.5     33.5     21.41   
26                     20111028120743        44       43     27.76   
27                     20111103103711      42.5     41.5     26.74   
28                     20111124082758        36       35     22.61   
29                     20120105115549      39.5     38.5      24.8   
..                                ...       ...      ...       ...   
216   Christop_-----312_-----358_043L      42.5     41.5     26.81   
217   Chrometz_-----401_----1227_041L        41       40     25.75   
218   Cizek---_-----849_----1146_000L        43       42     27.09   
219   Claus---_----2048_----3562_000L        41       40     25.89   
220   Clausen-_-----579_-----704_040L      40.5     39.5     25.54   
221   Conrad--_------88_------84_045L      43.5     42.5     27.59   
222   Conrad--_-----407_-----474_000L        33       32      20.6   
223   Conte---_-----908_----2930_000L      37.5     36.5     23.64   
224   Cramer--_----1214_----1798_000L        40       39     25.01   
225   Cronimus_----2265_----4083_000L        39       38     24.55   
226  Daeschlei_-----493_-----591_037L      36.5     35.5     22.82   
227   Dalibor-_-----850_----1148_047L        47       46     29.81   
228   Daninger_----2142_----4168_000L      38.5     37.5     24.02   
229   Dankwart_-----306_-----351_000L      43.5     42.5     27.41   
230   Dannert-_-----889_----1219_042L        42       41     26.49   
231   Danzer--_-----680_-----889_038L      38.5     37.5     24.17   
232   De Mario_-----321_----2650_000L        38       37     23.92   
233   Decker--_----1323_----2040_043L      42.5     41.5     26.74   
234   Degner--_----1370_----2131_035L        34       33     21.31   
235   Degner--_----1370_----4495_039L        39       38     24.48   
236   Deinzer-_----1265_----1926_045L      45.5     44.5     28.82   
237   Dembele-_----2369_----4308_000L      40.5     39.5     25.65   
238   Demireze_-----310_-----355_045L        45       44     28.54   
239   Denk----_-----988_----1393_036L      35.5     34.5      22.3   
240   Denk----_----2470_----4550_000L      38.5     37.5     24.31   
241   Denkler-_-----268_-----306_038L        

In [5]:
df.to_csv('data_length21_correctedfootscans.csv')
print('done')

done
